### ISSUE TITLE
chroot: can't execute '/bin/su': No such file or directory

### ISSUE THREAD

**Issue by mazhe1988** [mjuned47/Termux-Rootfs#1]
I am using lineage OS 18.1, magisk root, busybox installed with the latest version, 
When I run the install-20.10.sh, the error shows: chroot: can't execute '/bin/su': No such file or directory,
the only problem may be about the installation of busybox,  when I try to install it to the /system/xbin folder, it failed. So I install it in the /system/bin folder instead. I don't know if this is the issue to cause the problem. Or the latest Lineage OS is not compatible with this script?

**Comment by mazhe1988** [comment]
I figure out the error is cause by the wget command didn't download the tar file, shows bad address. I manually download it and put it in the /data/local/tmp folder. And now the installation process was succussed. I am now can chroot into the ubuntu as root.  But there is another issue come out. Seems like the required key fix didn't work in my case.  When I try to run apt update, it shows: Could not open lock file /var/lib/apt/lists/lock - open (126: Required key not available)

**Comment by mazhe1988** [comment]
I figure it out by myself. The reason of required key fix failure is that the script code which put the # sign in front of the relative files is not working. The awk command with 'session    optional   pam_keyinit.session force revoke' condition is not always match the case in my files. In this way, not all the relative line have been commented correctly. I need to manually put the # sign in front of the command line 'session    optional   pam_keyinit.session force revoke' of 4 files (which are the 'login', 'runuser', 'sunuser-l' and 'su-l' in the folder: /data/local/tmp/ubuntu/etc/pam.d/). After that the required key fix is successful. Because the required key failed, so the following internet fix is also not work during script running. I need to run the internet fix in the chroot as well in order to make the internet functional. Feel free to close this if there is nothing wrong about my statement.

**Comment by mjuned47** [comment]
Script was Fully working on my device with android version 7.
Above 7, there was an issue (required key) which i have resolved (by editing those 4 files) and checked whether those lines are commented or not 
Further there was same error but with different file(may be this 
 /var/lib/apt/lists/lock - open 126: Required key not available) i was not able to resolve it because error was not generating on my device but on other devices with higher android version(9,10,11)
Lastly, i have not work on script from last 3-4 months.

**Comment by mjuned47** [comment]
> I figure it out by myself. The reason of required key fix failure is that the script code which put the # sign in front of the relative files is not working. The awk command with 'session optional pam_keyinit.session force revoke' condition is not always match the case in my files. In this way, not all the relative line have been commented correctly. I need to manually put the # sign in front of the command line 'session optional pam_keyinit.session force revoke' of 4 files (which are the 'login', 'runuser', 'sunuser-l' and 'su-l' in the folder: /data/local/tmp/ubuntu/etc/pam.d/). After that the required key fix is successful. Because the required key failed, so the following internet fix is also not work during script running. I need to run the internet fix in the chroot as well in order to make the internet functional. Feel free to close this if there is nothing wrong about my statement.

If you are sure that script doesn't add # and script works after manually putting # on those lines then i can ask someone to test it. 
After that i will re upload

**Comment by mazhe1988** [comment]
I am sure it is only working on the login file not the rest of 3. I don't know if this is the reason or not. Because in my runuser file, the line looks like 'session optional pam_keyinit.session revoke', there is no 'force' between pam_keyinit.session and revoke. As you said, the rest of script work fine, after I manully put the # sign. And as I mentioned in the previous reply:  wget command didn't download the tar file. Because I test out the single wget command in my ternimal, it shows bad address. I don't know if this is caused by the url link is wrong？

**Comment by mjuned47** [comment]
No its not because of link.
If wget is not from busybox , it happens.
I might need to fix wget bad address

Have you changed ubuntu rootfs file link?
Because script is made according to rootfs which automatically download by it self

Someone have tested this and confirms that script works.
May be working because of Custom rom.

Let me know your android version, custom rom or not

**Comment by mazhe1988** [comment]
I am using lineage OS 18.1 base on Android 11, magisk rooted busybox 1.32 installed on system/bin, it fail to install on xbin. By the way, I am using termux terminal if it does matter. Run wget show: wget: bad address 'raw.githubusercontent.com'

**Comment by mazhe1988** [comment]
I search it online, I thought it may cause by the busybox and android rom. And something about the resolv.conf setting. It was nothing wrong about the script. Don’t worry about it. I will try to figure it out.

**Comment by mazhe1988** [comment]
I found the solution, the busybox wget in my rom need to set resovl.conf file, in order to avoid the bad address issue. To use 'echo "nameserver 8.8.8.8" > /system/etc/resolv.conf', one need to enbale /system in R/W model. The method for this probably different for each rom. I write the method for my case in lineage os 18.1 with default lineage recovery, in case anyone face the same problem as me (if you use the same rom as me).  You will need ADB interface available on you PC and connect your phone to your PC (If you install a custom ROM you should know how to do this, Otherwise google it). In my case, I am using windows.
1.  open cmd, type: 'adb devices' [enter] to make sure your phone is connected correctly, it should show your device code on the screen.
2. reboot to recovery mode, by typing: 'adb reboot recovery' [enter], wait the phone reboot and into recovery mode
3. click Advanced
4. click Mount/unmount system
5. click "back arrow" on the top left
6. click Reboot system now
7. after the phone reboot, in cmd type: adb root [enter]
8. type: adb remount [enter]
9. type: adb shell  [enter]
10. type: echo "nameserver 8.8.8.8" > /system/etc/resolv.conf [enter]
11. Done

If you have busybox installed correctly, you wget command should works. I have a suggestion on the script, to replace the 'wget' by 'busybox wget' to ensure using the wget binary from busybox to prevent any potential wrong.

**Comment by mazhe1988** [comment]
The following awk commands is working in my case. I think it may space sensitive as well
```
awk '/^session		optional	pam_keyinit.so force revoke/ { $0 = "#" $0 }; 1' $folder/etc/pam.d/login > $folder/etc/pam.d/login1
awk '/^session		optional	pam_keyinit.so revoke/ { $0 = "#" $0 }; 1' $folder/etc/pam.d/runuser > $folder/etc/pam.d/runuser1
awk '/^session		optional	pam_keyinit.so force revoke/ { $0 = "#" $0 }; 1' $folder/etc/pam.d/runuser-l > $folder/etc/pam.d/runuser-l1
awk '/^session		optional	pam_keyinit.so force revoke/ { $0 = "#" $0 }; 1' $folder/etc/pam.d/su-l > $folder/etc/pam.d/su-l1
```

**Comment by mjuned47** [comment]
So it doesn't need any additional solution, right?

**Comment by mazhe1988** [comment]
No, you can close this
