### ISSUE TITLE
Error in service module

### ISSUE THREAD

**Issue by Zeyrox1090** [mjuned47/Termux-Rootfs#2]
su: cannot open session: Error in service module
whenever i run start or install this shows up
![Screenshot_2021-12-02-23-04-33-95_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/73925046/144447754-5b5da6f1-f02c-465f-94b6-c71fa1ee0d39.jpg)
my phone is rooted android 10

**Comment by Zeyrox1090** [comment]
![Screenshot_2021-12-03-10-18-41-15_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/73925046/144533632-712c9343-a5b4-4215-af14-c2e105e32e27.jpg)

**Comment by mjuned47** [comment]
[Ubuntu-21.04-Script-by-ProLinux.zip](https://github.com/mjuned47/Termux-Ubuntu/files/7655201/Ubuntu-21.04-Script-by-ProLinux.zip)
Test this

**Comment by Zeyrox1090** [comment]
> [Ubuntu-21.04-Script-by-ProLinux.zip](https://github.com/mjuned47/Termux-Ubuntu/files/7655201/Ubuntu-21.04-Script-by-ProLinux.zip) Test this

![Screenshot_2021-12-11-14-08-54-11_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/73925046/145666304-6dcc04f0-0ba8-4fcf-bcf0-097ab765d8e9.jpg)

**Comment by Zeyrox1090** [comment]
still no

**Comment by mjuned47** [comment]
Fixed with Latest Release.
