### ISSUE TITLE
Getting 'Required key not available' with Ubuntu 21.04

### ISSUE THREAD

**Issue by w0nd3r365** [mjuned47/Termux-Rootfs#3]
@mjuned47  I'm still getting 'Required key not available' despite the fixing by the install script

![SmartSelect_20220215-030939_Termux](https://user-images.githubusercontent.com/97921087/153968433-6e915359-ba7c-43ad-8f3e-0c4206f71e62.jpg)

![SmartSelect_20220215-030902_Termux](https://user-images.githubusercontent.com/97921087/153968486-59b3ff46-5ee9-4cc8-a523-b021d098d432.jpg)

**Comment by mjuned47** [comment]
Fixed
